* Encoding: UTF-8.
DATASET ACTIVATE DataSet1.

DESCRIPTIVES VARIABLES=Gemiddeld_cijfer_WNS
  /STATISTICS=MEAN STDDEV.



GRAPH
  /HISTOGRAM=Gemiddeld_cijfer_WNS.


PPLOT
  /VARIABLES=Gemiddeld_cijfer_WNS
  /NOLOG
  /NOSTANDARDIZE
  /TYPE=Q-Q
  /FRACTION=BLOM
  /TIES=MEAN
  /DIST=NORMAL.

EXAMINE VARIABLES=Gemiddeld_cijfer_WNS 
  /COMPARE VARIABLE
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL
  /MISSING=LISTWISE.

NPAR TESTS
  /K-S(NORMAL)=Gemiddeld_cijfer_WNS
  /MISSING ANALYSIS.



T-TEST
  /TESTVAL=6.8
  /MISSING=ANALYSIS
  /VARIABLES=Gemiddeld_cijfer_WNS
  /CRITERIA=CI(.95).
