\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={One sample T-toets},
            pdfauthor={Irene van der Staaij \& Megiel Kerkhoven},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{One sample T-toets}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Irene van der Staaij \& Megiel Kerkhoven}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{1 Oktober 2019}


\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{gebruik}{%
\subsection{Gebruik}\label{gebruik}}

De \emph{One sample t-toets} kan gebruikt worden om aan de hand van één
steekproef het gemiddelde van de totale populatie te vergelijken met een
vooraf opgestelde hypothese \footnote{\href{https://wikistatistiek.amc.nl/index.php/T-toets\#one_sample_t-toets}{Wiki
  Statistiek Academisch Medisch Centrum}}.

\hypertarget{voorbeeld-uit-het-onderwijs}{%
\subsection{Voorbeeld uit het
onderwijs}\label{voorbeeld-uit-het-onderwijs}}

De opleidingsdirecteur van de opleiding Werktuigbouwkunde wil weten of
het gemiddelde eindexamencijfer voor de exacte vakken van haar VWO
studenten lager is dan het landelijke gemiddelde, zodat zij kan bepalen
of het curriculum van de inleidende vakken genoeg aansluiten bij de
eerstejaars studenten.

H\textsubscript{0}: Het gemiddelde eindexamencijfer voor de exacte
vakken van de VWO studenten die beginnen aan de Bachelor
Werktuigbouwkunde is hoger dan of gelijk aan het landelijk gemiddelde, µ
\textgreater= 6.8.

H\textsubscript{A}: Het gemiddelde eindexamencijfer voor de exacte
vakken van de VWO studenten die beginnen aan de Bachelor
Werktuigbouwkunde is lager dan het landelijk gemiddelde, µ \textless{}
6.8.

\hypertarget{normaliteit}{%
\subsection{Normaliteit}\label{normaliteit}}

De t-toets gaat er vanuit dat de data normaal verdeeld is, bij kleine
steekproeven is dit vaker niet het geval.

Controleer de data met deze stappen:\\
1. Controleer visueel door het maken van een dataplot: een histogram of
een boxplot.\\
2. Toets daarna of de data normaal verdeeld is met de Kolmogorov-Smirnov
Test of bij een kleinere steekproef met de Shapiro-Wilk Test \footnote{\href{https://wiki.uva.nl/methodologiewinkel/index.php/Normaliteit}{UvA
  Wiki Methodologiewinkel}}.

Wanneer uit bovenstaande tests blijkt dat de data niet normaal verdeeld
is, dus aan de assumptie niet wordt voldaan, dan kan de t-toets niet
gebruikt worden. Gebruik in dat geval de Wilcoxon Signed Rank Test.
\footnote{\url{http://r-statistics.co/Statistical-Tests-in-R.html}}

\hypertarget{uitvoering-in-r}{%
\subsection{Uitvoering in R}\label{uitvoering-in-r}}

Voor de uitvoering in R is er een dummydataset genaamd
gemiddeld\_cijfer\_wns ingeladen met de gemiddelde cijfers van Wiskunde,
Natuurkunde en Scheikunde van 122 middelbare scholieren.

\hypertarget{test-assumpties-normaliteit}{%
\subsubsection{Test assumpties:
normaliteit}\label{test-assumpties-normaliteit}}

Visualiseren van de data met behulp van een histogram

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(gemiddeld_cijfer_wns)}
\end{Highlighting}
\end{Shaded}

\includegraphics{01_One_sample_t-toets_files/figure-latex/histogram voor normaliteit-1.pdf}

De histogram laat een belvorm zien vergelijkbaar aan een
normaalverdeling, veel waardes liggen rondom het gemiddelde en weinig
bij de staarten van de verdeling. Daarnaast ziet de verdeling er in
grote mate symmetrisch uit.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

Toets normaliteit met de Kolmogorov-Smirnov Test of met de Shapiro-Wilk
Test (n \textless{} 50\footnote{\url{https://statistics.laerd.com/spss-tutorials/testing-for-normality-using-spss-statistics.php}~\\
  Open Intro Statistics Third Edition} ).

\hypertarget{section}{%
\subsubsection{}\label{section}}

\hypertarget{kolmogorov-smirnov}{%
\paragraph{Kolmogorov-Smirnov}\label{kolmogorov-smirnov}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(nortest)}
\KeywordTok{lillie.test}\NormalTok{ (gemiddeld_cijfer_wns)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  gemiddeld_cijfer_wns
## D = 0.053958, p-value = 0.5182
\end{verbatim}

De kolmogorov-smirnov test is een non-parametrische toets, die het
verschil in vorm tussen twee verdelingen toetst. In dit geval toetst
deze test het verschil tussen de normaalverdeling en de verdeling van de
steekproef.Wanneer de p-waarde kleiner is dan 0.05 is er een verschil
tussen beide verdelingen.

In dit geval is p \textgreater{} 0.05, dus is de verdeling van de data
niet significant verschillend van de normaalverdeling. Er wordt aan de
assumptie van normaliteit voldaan, dus de One sample-t-toets kan
uitvoerd worden.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{shapiro-wilk-test}{%
\paragraph{Shapiro-Wilk Test}\label{shapiro-wilk-test}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{shapiro.test}\NormalTok{(gemiddeld_cijfer_wns_n30)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  gemiddeld_cijfer_wns_n30
## W = 0.97612, p-value = 0.7158
\end{verbatim}

De Shapiro-Wilk Test is een soort gelijke test als de Kolmogorov-smirnov
test en wordt vooral gebruikt bij kleine steekproeven. Wanneer de
p-waarde groter is dan 0.05 is de verdeling van de data niet significant
verschillend van de normaalverdeling.

Ook bij deze test is p \textgreater{} 0.05, dus is er geen significant
verschil tussen de verdeling van de steekproef en de normaal verdeling.
Er wordt aan de assumptie van normaliteit voldaan, dus de One
sample-t-toets kan uitvoerd worden.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{one-sample-t-toets}{%
\subsubsection{One sample T-toets}\label{one-sample-t-toets}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(gemiddeld_cijfer_wns, }\DataTypeTok{mu =} \FloatTok{6.8}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  gemiddeld_cijfer_wns
## t = 3.7593, df = 121, p-value = 0.0002638
## alternative hypothesis: true mean is not equal to 6.8
## 95 percent confidence interval:
##  6.934637 7.234216
## sample estimates:
## mean of x 
##  7.084426
\end{verbatim}

Het gemiddelde van de steekproef is 7.08\\
Degrees of freedom (df) = n -1 = 122-1 = 121\\
p-waarde \textgreater{} 0.05, dus de H\textsubscript{0} wordt niet
verworpen.\\
95-betrouwbaarheidsinterval: Bij herhaling van het onderzoek zal in 95\%
van de gevallen een interval uitkomen waarbij µ in valt.

\hypertarget{rapportage}{%
\subsection{Rapportage}\label{rapportage}}

\hypertarget{verder-lezen}{%
\subsection{Verder lezen}\label{verder-lezen}}


\end{document}
