---
title: "Mann-Whitney U toets"
author: "Irene van der Staaij & Megiel Kerkhoven"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r versiegeschiedenis, include = FALSE, eval = FALSE}
## versie 0.1     3-9-19
```

```{r aanmaken data, include=FALSE, echo=TRUE}
RNGkind(sample.kind = "Rounding")
set.seed(0)

Goede_student_ec <- c(0, 3, 6, 6, 6, 6, 6, 6, 6)
Matige_student_ec <- c(0, 0, 0, 3, 6, 6, 6, 6, 6)
Slechte_student_ec <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6)

Resultaten_nl_studenten <- rbind (
                                  t(replicate(401, sample(Goede_student_ec, 11, replace = TRUE))), 
                                  t(replicate(203, sample(Matige_student_ec, 11, replace = TRUE))),
                                  t(replicate(309, sample(Slechte_student_ec, 11, replace = TRUE))))
Punten_jaar2_nl <- margin.table(Resultaten_nl_studenten, 1)

Resultaten_internationale_studenten <- rbind (
                                  t(replicate(250, sample(Goede_student_ec, 11, replace = TRUE))), 
                                  t(replicate(100, sample(Matige_student_ec, 11, replace = TRUE))),
                                  t(replicate(200, sample(Slechte_student_ec, 11, replace = TRUE))))
Punten_jaar2_inter <- margin.table(Resultaten_internationale_studenten, 1)

Resultaten_internationale_studenten <- data.frame(Resultaten_internationale_studenten, Punten_jaar2_inter)
Resultaten_nl_studenten <- data.frame(Resultaten_nl_studenten, Punten_jaar2_nl)

```

## 1 Toepassing

## 2 Onderwijscasus

## 3 Assumpties

## 4 Uitvoering in R

### De data bekijken
Gebruik `head()` in R om de eerste vijf regels te bekijken
```{r}
head(Resultaten_nl_studenten)
head(Resultaten_internationale_studenten)
```

### De Mann-Whitney U toets in R
Gebruik `wilcox.test()` met twee argumenten om een Mann-Whitney U toets te doen in R
```{r}
wilcox.test(Resultaten_nl_studenten$Punten_jaar2_nl, Resultaten_internationale_studenten$Punten_jaar2)
```

## Toelichting op de output

## 5 Rapportage

