---
title: "Gepaarde T-toets"
author: "Irene van der Staaij & Megiel Kerkhoven"
date: "1 Oktober 2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r aanmaken data, include=FALSE, echo=TRUE}
set.seed(2)

mu <- 3.6
sigma <- 0.6
evaluatie_rating_geen_tutor <- rnorm(250, mu, sigma)

evaluatie_rating_geen_tutor <- evaluatie_rating_geen_tutor[evaluatie_rating_geen_tutor <= 5 & evaluatie_rating_geen_tutor >= 1]
evaluatie_rating_geen_tutor <- sapply (evaluatie_rating_geen_tutor, round, 3)

mu <- 3.4
sigma <- 0.7
evaluatie_rating_wel_tutor <- rnorm(250, mu, sigma)

evaluatie_rating_wel_tutor <- evaluatie_rating_wel_tutor[evaluatie_rating_wel_tutor <= 5 & evaluatie_rating_wel_tutor >= 1]
evaluatie_rating_wel_tutor <- sapply (evaluatie_rating_wel_tutor, round, 3)

mu <- 3.6
sigma <- 0.6
evaluatie_rating_geen_tutor_n30 <- rnorm(30, mu, sigma)

evaluatie_rating_geen_tutor_n30 <- evaluatie_rating_geen_tutor_n30[evaluatie_rating_geen_tutor_n30 <= 5 & evaluatie_rating_geen_tutor_n30 >= 1]
evaluatie_rating_geen_tutor_n30 <- sapply (evaluatie_rating_geen_tutor_n30, round, 3)

mu <- 3.4
sigma <- 0.7
evaluatie_rating_wel_tutor_n30 <- rnorm(30, mu, sigma)

evaluatie_rating_wel_tutor_n30 <- evaluatie_rating_wel_tutor_n30[evaluatie_rating_wel_tutor_n30 <= 5 & evaluatie_rating_wel_tutor_n30 >= 1]
evaluatie_rating_wel_tutor_n30 <- sapply (evaluatie_rating_wel_tutor_n30, round, 3)
```

## Gebruik

## Voorbeeld uit het onderwijs

## Assumpties

## Uitvoering in R

### Normaliteit

```{r Assumptietest}
hist(evaluatie_rating_geen_tutor)
hist(evaluatie_rating_wel_tutor)
```

### {.tabset .tabset-fade .tabset.pills}
#### Lilliefors Test


```` {r Lilliefors Test, warning=FALSE}
library(nortest)
lillie.test(evaluatie_rating_geen_tutor)
lillie.test(evaluatie_rating_wel_tutor)
````


#### Shapiro-Wilk Test
``` {r Shapiro-Wilk Test, warning=FALSE}
shapiro.test(evaluatie_rating_geen_tutor_n30)
shapiro.test(evaluatie_rating_wel_tutor_n30)
```


### statistische toets in R

```{r statistische toets}
t.test(evaluatie_rating_wel_tutor, evaluatie_rating_geen_tutor, paired=TRUE)
```

## Toelichting op de output

## Rapportage

## Verder lezen

## Achtergrond info

