* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.

DESCRIPTIVES VARIABLES=Cijfers
  /STATISTICS=MEAN STDDEV.

IF  (Cohort = 2010) Cijfers_2010=Cijfers.
EXECUTE.

IF  (Cohort = 2011) Cijfers_2011=Cijfers.
EXECUTE.

DESCRIPTIVES VARIABLES=Cijfers_2010 Cijfers_2011
  /STATISTICS=MEAN STDDEV.

GRAPH
  /HISTOGRAM=Cijfers_2010.

GRAPH
  /HISTOGRAM=Cijfers_2011.

PPLOT
  /VARIABLES=Cijfers_2010 Cijfers_2011
  /NOLOG
  /NOSTANDARDIZE
  /TYPE=Q-Q
  /FRACTION=BLOM
  /TIES=MEAN
  /DIST=NORMAL.

EXAMINE VARIABLES=Cijfers BY Cohort
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL.

NPAR TESTS
  /K-S(NORMAL)=Cijfers_2010 Cijfers_2011
  /MISSING ANALYSIS.

T-TEST GROUPS=Cohort(2010 2011)
  /MISSING=ANALYSIS
  /VARIABLES=Cijfers
  /CRITERIA=CI(.95).
