---
title: "09 Friedman toets"
author: "© `r format(Sys.time(), '%Y')`, SURF Versnellingsagenda - Statistisch Handboek Hoger Onderwijs"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    theme: lumen
    toc: yes
    toc_float: 
      collapsed: FALSE 
    number_sections: true
  keywords: [statistisch handboek, studiedata]
---

<style>
`r htmltools::includeHTML(paste0(here::here(),"/01. Includes/css/Stylesheet_SHHO.css"))`
</style>

<!-- ## CLOSEDBLOK: Header.R -->
```{r header, include = FALSE, echo = TRUE, results='asis'} 
paste0(here::here(),"/01. Includes/code/Header.R")
```
<!-- ## /CLOSEDBLOK: Header.R -->

<!-- ## CLOSEDBLOK: Functiedefinities.R -->
```{r functiedefinities,include=FALSE, echo=TRUE}
library(stringr)
Round_and_format <- function(x, digits = 2) {
  x <- as.character(round(x, digits))
  x <- str_replace(x, "[.]", ",")
  return(x)
}
```
<!-- ## /CLOSEDBLOK: Functiedefinities.R -->

```{r aanmaken data, include=FALSE, echo=TRUE}



```

# Toepassing

# Onderwijscasus

# Assumpties

# Uitvoering in R

## Assumpties testen in R

```{r}

```

## Friedman toets

```{r}

```

# Toelichting op de output

# Rapportage

