name: deploy

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            jpeg
            ordinal
      - name: setup r-reticulate
        shell: Rscript {0}
        run: |
          reticulate::install_miniconda(force = TRUE)
          source(here::here("Python_Installatie_packages.R"))
      - name: create Python Rmd from chunks
        run: Rscript Index_Merge_Python.R
      - name: build
        run: Rscript Index_Render_site.R 
      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site

